### PR TITLE
feat: precise automatic installation of the scripts

### LINKED ISSUE #337: Full support for script
## Is your feature request related to a problem? Please describe.

apm already supports scripts with the "Install unlisted scripts" feature. However, since the name of the script is not shown in the list, there is a concern that people may think that apm can only use plugins.

## Describe the solution you'd like

Input the data as you did for the plugins.

## Additional context

When you are done adding scripts, apm will have covered most of the plugins and scripts in [aviutl.info](https://aviutl.info/) . This will be a good appeal point for apm.

### PR DESCRIPTION
**Pull request by mitosagi**
## Description

Improve the "Install unlisted scripts" feature. This will improve the stability of the feature by eliminating unrestricted installation of scripts from Amazonish. Scripts that cannot be installed automatically will be handled by falling back to the existing package data. The installed files will be placed in folders by author name to improve searchability within AviUtl.

This PR works with the data from https://github.com/hal-shu-sato/apm-data/pull/110 .

## Related Issue

- https://github.com/hal-shu-sato/apm-data/pull/110
  - It is preferable (but not required) to release this PR after the above PR has been distributed by jsDelivr.
- closes #337

## How Has This Been Tested?

Make sure to load https://github.com/hal-shu-sato/apm-data/pull/110 into apm.
- Clicking the Install button with the website selected will install the script.
- Pressing the Install button again on an installed script will not start the installation.
- If you click the Uninstall button or the Show Folder button with the website selected, a warning message will be displayed.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by hal-shu-sato — CHANGES_REQUESTED** [review]
In my environment, the browser is shown again after installing it.
Do you have any idea what that means?

**Comment by mitosagi** [comment]
It doesn't seem to be happening in my environment.
Does it happen with all scripts? Or is it a specific script?

**Comment by hal-shu-sato** [comment]
It happens in installing Ricky's or Satsuki's script...
I have no idea what caused it.

**Comment by hal-shu-sato** [comment]
In addition, UndoFish's easing script has the same problem.

**Comment by mitosagi** [comment]
I fixed that.

**Review by hal-shu-sato — APPROVED** [review]
It works correctly.

**Pull request merged**
