### PR TITLE
fix: fix for unexpected download of convert.json

### PR DESCRIPTION
**Pull request by mitosagi**
## Description

This is a fix for an issue where convert.json is downloaded at an unexpected time. if parseXML() downloads convert.json before convertId(), there will be inconsistencies in apmJson.

## How Has This Been Tested?

1. add id conversion from easymp4 to easymp4a (and update mod.xml)
2. click the Update Package Data button

Intended behavior
No change in apmJson.

Actual behavior
easymp4a is added to apmJson.

When parseXML is executed in setPackagesList(), the latest convert.json is downloaded from getIdDict. At this time, easymp4a is automatically added to apmJson because there is a file whose integrity matches.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by mitosagi** [comment]
[The deep copy in convertId.js:41](https://github.com/hal-shu-sato/apm/pull/281#pullrequestreview-841841756) was not causing any problems.

**Review by hal-shu-sato — APPROVED** [review]
Oh, I see.
Thank you for fixing it.

**Comment by hal-shu-sato** [comment]
I have shut down my PC. Could you please release v2.0.0 so that you can try release?

**Comment by mitosagi** [comment]
I'll try it.

**Comment by mitosagi** [comment]
The main branch is said to be protected, so I'll send it as a PR instead.

**Comment by hal-shu-sato** [comment]
Oh...
The problem can be solved only by creating an organization.
Do you think it is better to transfer this repository to an organization?

And can you force merge the PR?

**Comment by hal-shu-sato** [comment]
In addition, maybe there is a bug in creating release notes.
I think it is better to copy each section from the raw data of CHANGELOG.md.

**Comment by mitosagi** [comment]
I can't seem to force a merge. Isn't there a setting that allows merging without review from anyone?

**Comment by hal-shu-sato** [comment]
> I can't seem to force a merge. Isn't there a setting that allows merging without review from anyone?

Oh, I see the reason.
I removed it.

**Comment by mitosagi** [comment]
Are the release notes referring to the draft? It seems to be generated without any problem from here.

**Comment by hal-shu-sato** [comment]
> Are the release notes referring to the draft? It seems to be generated without any problem from here.

It looked like a few commits were missing, so I pointed them out.
I apologize if this was after I had sorted out the listing.

**Comment by mitosagi** [comment]
There were four drafts automatically created, so I misunderstood that they were related to past releases and deleted three of them. I'll add them by hand.

**Comment by hal-shu-sato** [comment]
Thanks.
If you think there is an unnecessary note, you can delete it for readability.

**Comment by mitosagi** [comment]
Can I press the release button?

**Comment by hal-shu-sato** [comment]
Can I take a moment to add an announcement of my break at the first and my mention to the Contributors section?

**Comment by hal-shu-sato** [comment]
I have added it.
You can release v2.0.0!!🎉

**Pull request merged**
