### PR TITLE
Support dependencies

### PR DESCRIPTION
**Pull request by mitosagi**
## Description

Supports dependency features.

**This PR depends on the following PRs.**
- #153 
- https://github.com/hal-shu-sato/apm-data/pull/28

## Motivation and Context

In fact, I was aiming for a feature that would allow to install the entire dependency. However, it seemed difficult, so I simplified the implementation.

## How Has This Been Tested?

- Packages that do not have a parent installed will be marked with ❗.
- ⚠️ will be displayed for packages that cannot be installed in the installed version of aviutl or exedit.
- If a package cannot be installed because another version of the package is installed, ⚠️ will be displayed.
- Filtering by installation state still works.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by hal-shu-sato** [comment]
I'm sorry to be late with the review.
I don't have enough time to review it.
Please wait for a while.

**Comment by mitosagi** [comment]
Rebased. The code has not been changed.

**Review by hal-shu-sato — APPROVED** [review]
Good!
It's also good to have common messages.
Sorry for the late review.

**Comment by hal-shu-sato** [comment]
I also think it is good to use Twemoji for design.

**Comment by mitosagi** [comment]
It's certainly a good idea to make sure that emoji look the same on different devices.

What are common messages?

**Comment by hal-shu-sato** [comment]
> What are common messages?

It means the messages in the `state` object you made.

**Pull request merged**
