### PR TITLE
feat: support for data v2 core.xml

### PR DESCRIPTION
**Pull request by mitosagi**
## Description

Supports data v2 `core.xml`. Please use the data v1 `packages_list.xml` and `mod.xml` for testing.

## Related Issue

- #235

## How Has This Been Tested?

- If you start apm after deleting `apm.json`, the correct version will be reconfigured.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by mitosagi** [comment]
There was an error in downloading the library, so I rerun the CI.

**Review by hal-shu-sato — APPROVED** [review]
It looks good!
I'll test this later.

**Comment by hal-shu-sato** [comment]
Sorry.
I'd like to maintain the compatibility of v1.
So I think to separate `parseXML.js` and change the parsing process depending on the data version.

**Comment by mitosagi** [comment]
I will write a migration of dataURL in a subsequent PR, so reading v1 will no longer be necessary.

**Review by hal-shu-sato — APPROVED** [review]
It works correctly.

**Pull request merged**
