### PR TITLE
refactor(parseXML): change to use the library to parse XML

### LINKED ISSUE #57: Library for parsing XML
## Is your feature request related to a problem? Please describe.

Parsing XML is complicated, so it is better to separate processes to parse XML.
#55 

## Describe the solution you'd like

- Make classes of lists of plugins or scripts.
- Separate process for parsing XML.

### PR DESCRIPTION
**Pull request by hal-shu-sato**
## Description

Changes to use the library to parse XML.

## Related Issue

Closes #57 

## How Has This Been Tested?

OS: Windows 10 Home
Version: 21H1

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by hal-shu-sato** [comment]
@mitosagi If you have time, could you check this PR?

**Comment by mitosagi** [comment]
I'll check it out.

**Review by mitosagi — APPROVED** [review]
It looks good to me.

**Comment by hal-shu-sato** [comment]
Thank you for reviewing!!
If you have any suggestions on how to improve this, please let me know.

**Pull request merged**
