### PR TITLE
docs: update readme

### PR DESCRIPTION
**Pull request by mitosagi**
## Description

Update the readme to reflect the contents of #156 . I will write the English version after the Japanese version is accepted.

**This PR depends on the following PRs.**
- #156

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by hal-shu-sato — COMMENTED** [review]
I didn't notice, but APM is capitalized.
I prefer to use lower case to match npm, but which is better?
Let's unify at this point.

**Comment by mitosagi** [comment]
I wasn't particularly conscious of it, so I used capital letters. Whichever you prefer is fine.

**Comment by hal-shu-sato** [comment]
I still prefer lowercase because it's cute.
Let's use lowercase letters.

**Comment by mitosagi** [comment]
I've reflected it.

**Review by hal-shu-sato — APPROVED** [review]
Good readme!
Thank you for reflecting.

**Comment by hal-shu-sato** [comment]
And, I've changed the theme of the page to `minimal`.
Please check it and let me know if you have an idea.

**Pull request merged**
