### PR TITLE
feat(log): add the feature to log uncaught exceptions and exit

### PR DESCRIPTION
**Pull request by hal-shu-sato**
## Description

Add the feature to log uncaught exceptions and exit.
If you want more information, you can add a log.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by mitosagi — COMMENTED** [review]
In my environment, after adding the code below to `main.js: 281`, the event caused an error, but no dialog was displayed.
```
throw new Error('database failed to connect');
```

**Comment by hal-shu-sato** [comment]
I couldn't reproduce that.
It may be because of the timing of emitting a `ready` event.

**Review by mitosagi — APPROVED** [review]
It worked correctly in `main.js:409`. It seems to work in the main process, but not in the ipc or render process. I think this is a reasonable behavior.

It might be nice to have the ability to save render process errors to log as well.

**Comment by hal-shu-sato** [comment]
OK.
I'll add logging for the render process and request review again.

**Comment by hal-shu-sato** [comment]
I added them.
I found a better method to do this so I changed the process.

**Comment by mitosagi** [comment]
The error message is displayed even in the case of an expected error, such as pressing the install button with nothing selected. In this case, can I remove the line that rethrows the error? ( e.g. package.js: 558)

**Comment by hal-shu-sato** [comment]
Certainly.
I think it is better to replace it with `log.error(msg)` and `return`.

**Comment by mitosagi** [comment]
Yes, let's merge it.

**Pull request merged**
