### PR TITLE
feat(package maker): support for installers

### PR DESCRIPTION
**Pull request by mitosagi**
## Description

Changes to the package manager.

- Support for mirror URLs
- Support for installers
- Fixes to detection of inconsistent file structures
- Other modifications

Sorry the diff is hard to see.

## Motivation and Context

To make it easier to enter plugins from `rigaya` that use installer or mirror URLs.

## How Has This Been Tested?

The intended XML will be generated

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by hal-shu-sato** [comment]
> > hal-shu-sato added this to 🛠In progress in New Features via automation
> 
> How do you always do this? Who should be assigned to Assignees?

It will be shown when the project is assigned.
"Projects" will be found below labels.

**Comment by mitosagi** [comment]
Thank you. I tried.

**Comment by hal-shu-sato** [comment]
Can I merge this PR?
Or should I wait for you?

**Comment by mitosagi** [comment]
Please wait a moment while I fix the data id.

**Comment by mitosagi** [comment]
Fixed it.

**Review by hal-shu-sato — APPROVED** [review]

**Pull request merged**
