### PR TITLE
feat: support for data v2 packages.xml and migration

### PR DESCRIPTION
**Pull request by mitosagi**
## Description

Supports data v2, upgradable from v1. I will not implement integrity in this PR.

**This PR depends on the following PR(s).**
- #243
- #244

## Related Issue

- #245

## How Has This Been Tested?

- It works fine with a clean install.

Update from v1
- The URL from which data is retrieved has been updated.
- The cache of v1 will be deleted.
- Packages added by the script installation feature not listed in the table will be correctly inherited.
- The repository URL in apm.json is updated.
- The id in the apm.json will be updated to that of v2.
- Version numbers are added to electron-store and apmJson.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by hal-shu-sato — CHANGES_REQUESTED** [review]
I have some points to change.

It is better to ask users this before migration:
- apm migrates to default settings.
- apm migrates to settings that support another data repository.
- apm doesn't migrate and end the app.

I think possibly some users changed their data repository.
I’d like to support them.

I'd like to support ID conversion in any repository at all times.
It will be useful when the repository owner makes a mistake in the ID.

**Comment by mitosagi** [comment]
I would like to make the following changes:
1. Do not initialize `dataURL.extra`. Continue to make `packages_list.xml` available.
2. If `dataURL.main` is not JsDeliver, a dialog will appear.
   - If "Use default data repository" is pressed, initialize `dataURL.main` and start apm (current behavior).
   - If "Quit apm" is pressed, quit apm.
3. Perform id conversion transparently during XML parsing.

**Comment by mitosagi** [comment]
I made the changes mentioned in the comments above.

Introduced a new library (electron-prompt) to emit a text dialog.

**Review by hal-shu-sato — APPROVED** [review]
It works correctly.
I think some points can be improved more, but we can fix them after merging.

**Pull request merged**
