### PR TITLE
feat: use webpack and other tools

### LINKED ISSUE #315: ESModule
## Is your feature request related to a problem? Please describe.

Some packages use ESModule and apm can't use them now.
Also, the use of ESModule is slowly becoming mainstream.
And, I heard ESModule can import CommonJS Module too.

## Describe the solution you'd like

Use ESModule.

### PR DESCRIPTION
**Pull request by mitosagi**
## Description

Based on the guide of [Electron Forge](https://www.electronforge.io/guides/framework-integration/react-with-typescript), supports webpack, TypeScript, React, and ESModule.

### Known Issues (I could not fix)
- Increased build time
- It is no longer possible to write references to specific CSS in HTML files. This is because references to images, etc. from CSS loaded in webpack's html-loader are not parsed. Instead, put references to CSS in `renderer.js`. Specific CSS include Twemoji for font files and Bootstrap-icons for images.
- It is not possible to update major versions of webpack or change to a build system other than webpack unless electron-forge supports it.
- ~~There is a mix of default export and named export with no clear policy regarding ESmodule support.~~

## Related Issue

- #313
- #314
- closes #315

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] ~~I have updated the documentation accordingly.~~ I will do it later.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by yumetodo** [comment]
note: Webpack sometimes introduce too much complexity which could block to follow webpack major version up. It could be good for maintainability to limit webpack flexibility into command-line option, not config file.

**Comment by mitosagi** [comment]
I didn't know that webpack can be used without preparing a config file. Thank you for telling me about it.

Unfortunately, due to the limitations of the Electron build tool we use, I can' t seem to give command line arguments and can' t change the contents of the config file much.

**Comment by yumetodo** [comment]
https://webpack.js.org/api/cli/ is official document for using webpack via command-line. Now I got it is not suite for electron app to build via command-line. Don't forget that you need time more than you are expecting when webpack major version up has occurred.

**Comment by mitosagi** [comment]
Packaging now stops on lint failure.

**Comment by hal-shu-sato** [comment]
> ### Known Issues (I could not fix)
> * Increased build time

I think that it happens because `electron-forge` has to compile `.ts` files to `.js` files.
So, we have to compromise.

> * It is no longer possible to write references to specific CSS in HTML files. This is because references to images, etc. from CSS loaded in webpack's html-loader are not parsed. Instead, put references to CSS in renderer.js. Specific CSS include Twemoji for font files and Bootstrap-icons for images.

I see.
(Do you think this will occur with Webpack's React support and can be fixed by migrating React?)

> * It is not possible to update major versions of webpack or change to a build system other than webpack unless electron-forge supports it.

`webpack` is included in `@electron-forge/plugin-webpack` so if `plugin-webpack` updates its `webpack` version, the dev team will notify us that as a breaking change.
And, I don't know about other build systems. Do you know any ones?

> * There is a mix of default export and named export with no clear policy regarding ESmodule support.

I read these articles:
https://engineering.linecorp.com/ja/blog/you-dont-need-default-export/
https://zenn.dev/yuhr/articles/668dba202726bf
https://jsnotice.com/posts/2021-01-30/

I think that we should use the default export after naming the function or object.
What do you think about this?

**Comment by mitosagi** [comment]
> > * It is no longer possible to write references to specific CSS in HTML files. This is because references to images, etc. from CSS loaded in webpack's html-loader are not parsed. Instead, put references to CSS in renderer.js. Specific CSS include Twemoji for font files and Bootstrap-icons for images.
> 
> I see.
> (Do you think this will occur with Webpack's React support and can be fixed by migrating React?)

I believe this is due to the html-loader not being properly configured; React is not affected as it is called in renderer.js.

> > * It is not possible to update major versions of webpack or change to a build system other than webpack unless electron-forge supports it.
> 
> `webpack` is included in `@electron-forge/plugin-webpack` so if `plugin-webpack` updates its `webpack` version, the dev team will notify us that as a breaking change.
> And, I don't know about other build systems. Do you know any ones?

I certainly agree. I was thinking of other build systems such as vite and esbuild which are sometimes used along with electron-builder.

> > * There is a mix of default export and named export with no clear policy regarding ESmodule support.
> 
> I read these articles:
> https://engineering.linecorp.com/ja/blog/you-dont-need-default-export/
> https://zenn.dev/yuhr/articles/668dba202726bf
> https://jsnotice.com/posts/2021-01-30/
> 
> I think that we should use the default export after naming the function or object.
> What do you think about this?

It looks very good and I would like to write the export in that way. Also, the import statement is converted as follows by vscode's automatic conversion function, but I'll revert it as before.

```javascript
// Before conversion
import fs from 'fs-extra';
fs.existsSync(...);

// After conversion
import { existsSync } from 'fs-extra';
existsSync(...);
```

**Comment by hal-shu-sato** [comment]
> > > * It is no longer possible to write references to specific CSS in HTML files. This is because references to images, etc. from CSS loaded in webpack's html-loader are not parsed. Instead, put references to CSS in renderer.js. Specific CSS include Twemoji for font files and Bootstrap-icons for images.
> > 
> > I see.
> > (Do you think this will occur with Webpack's React support and can be fixed by migrating React?)
> 
> I believe this is due to the html-loader not being properly configured; React is not affected as it is called in renderer.js.

I see... (Building is so difficult...😭)

I find babel-loader using babel.
But I don't know well about babel.

> > > * It is not possible to update major versions of webpack or change to a build system other than webpack unless electron-forge supports it.
> > 
> > `webpack` is included in `@electron-forge/plugin-webpack` so if `plugin-webpack` updates its `webpack` version, the dev team will notify us that as a breaking change.
> > And, I don't know about other build systems. Do you know any ones?
> 
> I certainly agree. I was thinking of other build systems such as vite and esbuild which are sometimes used along with electron-builder.

I see... I learned they are not supported by electron-forge but they maybe reduce build time...
And I also learned esbuild has esbuild-loader. It possibly shortens build time.

> > > * There is a mix of default export and named export with no clear policy regarding ESmodule support.
> > 
> > 
> > I read these articles:
> > https://engineering.linecorp.com/ja/blog/you-dont-need-default-export/
> > https://zenn.dev/yuhr/articles/668dba202726bf
> > https://jsnotice.com/posts/2021-01-30/
> > I think that we should use the default export after naming the function or object.
> > What do you think about this?
> 
> It looks very good and I would like to write the export in that way. Also, the import statement is converted as follows by vscode's automatic conversion function, but I'll revert it as before.
> 
> ```js
> // Before conversion
> import fs from 'fs-extra';
> fs.existsSync(...);
> 
> // After conversion
> import { existsSync } from 'fs-extra';
> existsSync(...);
> ```

OK.
In searching, I find tree shaking, which reduce bundled module.
I don't know how the change affect the tree shaking but I want to use the feature to reduce app size...

----

There are many points to think in order to use typescript and react...
It may be a good idea to put together the current plan once and discuss it on the issue.

**Comment by hal-shu-sato** [comment]
I found these packages.
I still want to use webpack because electron-forge supports this.
Should I migrate to electron-builder?

## Summary

### Electron Building

- electron-forge (Now using, uses electron-packager)
- electron-builder

### Build System

- webpack (supported by electron-forge)
- Vite (supports Vue and React, uses esbuild)
- esbuild (using Go, don't check type but we can use `tsc --noEmit` or ts-node)

### webpack's loader

#### HTML

- html-loader

#### CSS

- css-loader + style-loader
- (css-loader + style-loader + sass-loader)

#### JavaScript / TypeScript

- ts-loader
- babel-loader (don't check type)
- esbuild-loader (uses esbuild, read above)

#### Node.js

- node-loader

#### Performance

- thread-loader

**Comment by mitosagi** [comment]
I think it would be very difficult to come up with our own webpack configuration and it would be very hard to maintain. This PR is currently using the [TypeScript + Webpack template](https://www.electronforge.io/guides/framework-integration/react-with-typescript) from electron-forge, and would like to keep that configuration unless there is some outstanding advantage from it.

**Comment by hal-shu-sato** [comment]
Yes.
Since our initial goal is to migrate to TypeScript and React, we should consider the build performance, etc. after the migration is complete.

**Comment by mitosagi** [comment]
Rebased.
I have changed eslint rules to allow commonjs to handle files that are not transpiled.

**Comment by hal-shu-sato** [comment]
If we use `ts-node`, we can use TypeScript for the webpack configuration file, but is it superfluous?

**Comment by hal-shu-sato** [comment]
> If we use `ts-node`, we can use TypeScript for the webpack configuration file, but is it superfluous?

I'll do this after this PR is merged.
I'll rebase this PR on my local environment (resolve conflict by `yarn install`) and merge.

**Review by hal-shu-sato — APPROVED** [review]
All features work fine.

**Comment by hal-shu-sato** [comment]
I merged this PR at https://github.com/hal-shu-sato/apm/commit/e9823cdb64c300ab5037c655d3e3a013c50f2ac9.

**Comment by mitosagi** [comment]
Thanks for the rebase and merge.

I think there are few chances to change the configuration file, so I personally don't plan to introduce `ts-node`.

**Comment by hal-shu-sato** [comment]
OK. I see. Introduce it when editing configuration files.

**Pull request closed without merging**
