### PR TITLE
style: change tab width from 4 to 2

### PR DESCRIPTION
**Pull request by hal-shu-sato**
## Description

Change tab width from 4 to 2

## Motivation and Context

These days, the code becomes longer and longer, so it becomes hard to read.
Reduce the tab width to reduce reading difficulty.

## How Has This Been Tested?

OS: Windows 10 Home
Version: 21H1

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by mitosagi — APPROVED** [review]
It looks good to me.

**Comment by hal-shu-sato** [comment]
Thanks.
I'll release v1.0.0 at 12:00.
Is it OK?

**Comment by mitosagi** [comment]
I think we' re ready. I can't wait for the release!

**Comment by mitosagi** [comment]
Wait a minute.

**Comment by hal-shu-sato** [comment]
I don't have that error...

**Comment by mitosagi** [comment]
It worked on the second startup, so I guess I'm wrong.

**Comment by hal-shu-sato** [comment]
If you delete your config and start-up, does any error occur?
I think if it doesn't, users can use it surely.

**Comment by mitosagi** [comment]
On the contrary, it will only occur immediately after deletion.

**Comment by hal-shu-sato** [comment]
Umm...
We should fix it...

**Comment by hal-shu-sato** [comment]
Do you send an issue?
I'll try it one more time.

**Comment by hal-shu-sato** [comment]
@mitosagi 
OK. I'll release it!!

**Comment by hal-shu-sato** [comment]
Anyhow, I released it!!

**Comment by mitosagi** [comment]
Great job. I've received an update to my installation version.

I just wanted to say at this point that I really appreciate the time you took to make the repository available for participation and to review the PR. Thank you very much.

**Comment by hal-shu-sato** [comment]
We would not have been able to release it at this speed without you, our collaborator.
Thank you very much too!!!!

**Pull request merged**
