### PR TITLE
refactor: separate files for renderer process

### PR DESCRIPTION
**Pull request by hal-shu-sato**
## Description

- Separate files for renderer process.

If you have any opinion, please let me know.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by hal-shu-sato** [comment]
If you have any opinion, especially about the filename, please let me know.

**Review by yumetodo — APPROVED** [review]
LGTM

```diff
-src/about_renderer.ts
+src/renderer/about/about_renderer.ts
```

BTW, Why git doesn't recognize as file move...

**Comment by hal-shu-sato** [comment]
Thanks.

> BTW, Why git doesn't recognize as file move...

I searched Git's process and find that the `git mv` command moves the file and adds and removes it from Git.
(Refer to https://tech1313.hatenablog.com/entry/2021/02/28/144145)

And I also find Git decides whether the file was renamed by the similarity of the deleted file and created file.
(Refer to https://zenn.dev/yoichi/articles/how-git-handles-renaming)
So, maybe GitHub may detect renaming by 50% similarity(default).
Perhaps there is no need to be overly concerned about that.

**Comment by mitosagi** [comment]
What is the difference between `src/lib` and `src/renderer/main/lib`?

**Comment by hal-shu-sato** [comment]
The files in `src/renderer/main/lib` depend on files in `src/renderer/main`.
So I separate them from other lib files.

**Review by mitosagi — APPROVED** [review]
The `CONTRIBUTING.md` should be changed at the time of migration to v3.

**Pull request merged**
