### PR TITLE
feat: add a menu to send a feedback

### LINKED ISSUE #117: Add feedback button
## Is your feature request related to a problem? Please describe.

It is hard to know where users can send feedback.

## Describe the solution you'd like

Add a button to open the issue page in the menu.

### PR DESCRIPTION
**Pull request by hal-shu-sato**
## Description

Add a button to send feedback in the upper menu.
Do you think the page opened is appropriate?

## Related Issue

Close #117 

## Motivation and Context

Reference #117 

## How Has This Been Tested?

OS: Windows 10 Home
Version: 21H1

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by mitosagi** [comment]
I would prefer a link to the issue list so that contributors can see if there are any duplicate issues.

**Comment by hal-shu-sato** [comment]
I see.
It's better.

**Comment by hal-shu-sato** [comment]
I fixed.

**Review by mitosagi — APPROVED** [review]
It looks good.

**Pull request merged**
