### PR TITLE
feat(convertId): add a feature to convert IDs

### PR DESCRIPTION
**Pull request by hal-shu-sato**
## Description

Add the feature to convert IDs at startup and when changing the installation path.

## Related Issue

- #245
- hal-shu-sato/apm-data#81

## How Has This Been Tested?

It has run at startup and when changing the installation path.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by mitosagi — CHANGES_REQUESTED** [review]
I think it would be simpler to remove getIdDict and L197-206 from migration1to2.js, which is duplicate code, although it would mean writing a cacheable getIdDict to call from parseXML.

This is my coding mistake, but sometimes there was a bug where the previous id was not deleted. convertId.js:41 may need to use a deep copy of the packages object.

**Comment by hal-shu-sato** [comment]
> I think it would be simpler to remove getIdDict and L197-206 from migration1to2.js, which is duplicate code, although it would mean writing a cacheable getIdDict to call from parseXML.

There is a problem that comes from the circulation of `require`.
We have to refactor before doing this.

**Comment by mitosagi** [comment]
You may have already done this, but what about moving the mod from convertId to preload?

**Comment by hal-shu-sato** [comment]
Oh, I'll try it maybe tomorrow.

But I have to study for my exam, so I do not have much time.
So can you fix convertId.js:41 after merging this PR?

Also, I will not able to develop apm from January to around the end of March.
So, may I entrust you with the development of apm?
I'll create issues for all the ideas I'm working on, and I'll also write down the release instructions, so you can release apm under the collaborator's authority.
If you can't, I think it's okay to stop or slow down development for about 3 months.
What do you think?

**Comment by mitosagi** [comment]
Okay, I'll fix convertId.js:41.

As for the next three months, I am not going to release new features without your review.  So I will try to slow down the pace of development and do only small things like fixing bugs and updating dependencies.

**Comment by hal-shu-sato** [comment]
I fixed.

**Comment by hal-shu-sato** [comment]
> Okay, I'll fix convertId.js:41.

Thank you.
 
> As for the next three months, I am not going to release new features without your review. So I will try to slow down the pace of development and do only small things like fixing bugs and updating dependencies.

OK. Thanks.
I tell you how to release apm just in case.

First, set your environment variable `CONVENTIONAL_GITHUB_RELEASER_TOKEN` to the token you just created. 
(Refer to https://www.npmjs.com/package/conventional-github-releaser#setup-token-for-cli)

Then, on the `main` branch, run `yarn release` and `git push origin main --follow-tags`.
The new version will be decided automatically depending on commit messages, but you can set the option of `release:patch`(ex. v2.0.1), `release:minor`(ex. v.2.1.0), or `release:major`(ex. v3.0.0).
(The examples are the new version from `v2.0.0`.)

After that, open https://github.com/hal-shu-sato/apm/releases, and you will see the draft.
If you can, please translate the changelog into Japanese.
Finally, release the version.

I apologize for any inconvenience this may cause and thank you in advance.

**Review by mitosagi — APPROVED** [review]
Good feature.

**Comment by mitosagi** [comment]
Thank you for sharing the release procedure. I'll use it if I have to.

I'll send you two more bug-fix commits and I'd be happy to release 2.0 after that.

**Comment by hal-shu-sato** [comment]
OK. Sure.

**Pull request merged**
