### PR TITLE
feat(userData&Store): separate data for production and development

### PR DESCRIPTION
**Pull request by mitosagi**
## Description

Saves the data of the development version and the production version in different locations. This allows you to develop a new version of the product without having to change the data of the product in use.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by hal-shu-sato — COMMENTED** [review]
I apologize for the delay.
I would like to check it on my computer, but I haven't been able to find the time.

**Review by hal-shu-sato — COMMENTED** [review]
@mitosagi 
I think the name of the data directory should be `_Dev` rather than `_Debug`, what do you think?

**Comment by mitosagi** [comment]
You're right.

**Review by hal-shu-sato — APPROVED** [review]
Thank you for fixing it.
Good improvement.

**Pull request merged**
