### PR TITLE
docs: add landing page

### PR DESCRIPTION
**Pull request by mitosagi**
## Description

Make the apm web page look like a landing page. I think it will make downloading even easier.

- I apologize that you'll have to rewrite the download link for every release from now on.
- I wanted to include the apm logo, but it was difficult to find a good fit with the current jekyll theme, so I can' t include it.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by hal-shu-sato — CHANGES_REQUESTED** [review]
I think it is not necessary to delete old configs because they don't affect and L1-53 in `_config.yml` are default settings of Jekyll.

**Comment by mitosagi** [comment]
I fixed it.

**Review by hal-shu-sato — CHANGES_REQUESTED** [review]
Did you forget to change the theme?
```yaml
theme: jekyll-theme-cayman
```

**Comment by mitosagi** [comment]
Sorry. Fixed it.

**Review by hal-shu-sato — COMMENTED** [review]
The change is needed only when we use a theme that is not included in GitHub Pages.
`cayman` is a GitHub-Pages-included theme, so we can use it this way.
```yaml
theme: jekyll-theme-cayman
```

**Comment by mitosagi** [comment]
Okay, I understand.

**Review by hal-shu-sato — APPROVED** [review]
Thank you for fixing it so many times.
Good page.

**Pull request merged**
